 
$background = rgb(0e1513)

$error = rgb(ffb4ab)

$error_container = rgb(93000a)

$inverse_on_surface = rgb(2b3230)

$inverse_primary = rgb(006a60)

$inverse_surface = rgb(dde4e1)

$on_background = rgb(dde4e1)

$on_error = rgb(690005)

$on_error_container = rgb(ffdad6)

$on_primary = rgb(003731)

$on_primary_container = rgb(9ef2e4)

$on_primary_fixed = rgb(00201c)

$on_primary_fixed_variant = rgb(005048)

$on_secondary = rgb(1c3531)

$on_secondary_container = rgb(cce8e2)

$on_secondary_fixed = rgb(05201c)

$on_secondary_fixed_variant = rgb(334b47)

$on_surface = rgb(dde4e1)

$on_surface_variant = rgb(bec9c6)

$on_tertiary = rgb(153349)

$on_tertiary_container = rgb(cce5ff)

$on_tertiary_fixed = rgb(001e31)

$on_tertiary_fixed_variant = rgb(2d4961)

$outline = rgb(899390)

$outline_variant = rgb(3f4947)

$primary = rgb(82d5c8)

$primary_container = rgb(005048)

$primary_fixed = rgb(9ef2e4)

$primary_fixed_dim = rgb(82d5c8)

$scrim = rgb(000000)

$secondary = rgb(b1ccc6)

$secondary_container = rgb(334b47)

$secondary_fixed = rgb(cce8e2)

$secondary_fixed_dim = rgb(b1ccc6)

$shadow = rgb(000000)

$source_color = rgb(1a4e47)

$surface = rgb(0e1513)

$surface_bright = rgb(343b39)

$surface_container = rgb(1a211f)

$surface_container_high = rgb(252b2a)

$surface_container_highest = rgb(303635)

$surface_container_low = rgb(161d1b)

$surface_container_lowest = rgb(090f0e)

$surface_dim = rgb(0e1513)

$surface_tint = rgb(82d5c8)

$surface_variant = rgb(3f4947)

$tertiary = rgb(adcae6)

$tertiary_container = rgb(2d4961)

$tertiary_fixed = rgb(cce5ff)

$tertiary_fixed_dim = rgb(adcae6)

